spring:
  config:
    activate:
      on-profile: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL_LOCAL}
    username: ${SPRING_DATASOURCE_USERNAME_LOCAL}
    password: ${SPRING_DATASOURCE_PASSWORD_LOCAL}

  data:
    redis:
      host: ${REDIS_HOST_LOCAL}
      port: ${REDIS_PORT_LOCAL}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.harusari.chainware

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-stacktrace: never

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha